services:
    Rector\Rector\Contrib\PhpParser\IdentifierRector: ~
    Rector\Rector\Contrib\PhpParser\ParamAndStaticVarNameRector: ~
    Rector\Rector\Contrib\PhpParser\CatchAndClosureUseNameRector: ~
    Rector\Rector\Contrib\PhpParser\SetLineRector: ~
    Rector\Rector\Contrib\PhpParser\RemoveNodeRector: ~
    Rector\Rector\Contrib\PhpParser\UseWithAliasRector: ~

    Rector\Rector\Dynamic\PropertyNameReplacerRector:
        $perClassOldToNewProperties:
            'PhpParser\Node\Stmt\Class_':
                'type': 'flags'
            'PhpParser\Node\Stmt\ClassMethod':
                'type': 'flags'
            'PhpParser\Node\Stmt\Property':
                'type': 'flags'

    Rector\Rector\Dynamic\ClassConstantReplacerRector:
        $oldToNewConstantsByClass:
            'PhpParser\Node\Stmt\Class_':
                'VISIBILITY_MODIFER_MASK': 'VISIBILITY_MODIFIER_MASK'

    Rector\Rector\Dynamic\ClassReplacerRector:
        $oldToNewClasses:
            'PhpParser\BuilderAbstract': 'PhpParser\Builder'
