services:
    _defaults:
        autowire: true

    Rector\PharBuilder\:
        resource: '../'
        public: true

    # Symfony\Console
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: Symfony\Component\Console\Input\ArgvInput

    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput
