parameters:
    # customizable (via %ENV()?)
    pharName: 'rector.phar'
    binFileName: 'bin/rector'

services:
    _defaults:
        autowire: true
        bind:
            $pharName: '%pharName%'
            $binFileName: '%binFileName%'

    Rector\PharBuilder\:
        resource: '../'
        public: true

    # Symfony\Console
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']
