services:
    _defaults:
        autowire: true

    Rector\Rector\Contrib\Nette\Application\ValidateControlRectorProvider: ~

    Rector\Rector\Contrib\Nette\Utils\NetteObjectToSmartTraitRector: ~
    Rector\Rector\Contrib\Nette\Utils\MagicMethodRector: ~

    # application
    Rector\Rector\Contrib\Nette\Application\TemplateMagicInvokeFilterCallRector: ~
    Rector\Rector\Contrib\Nette\Application\TemplateRegisterHelperRector: ~

    # di
    Rector\Rector\Contrib\Nette\DI\SetEntityToStatementRector: ~
    Rector\Rector\Contrib\Nette\DI\ExpandFunctionToParametersArrayRector: ~
    Rector\Rector\Contrib\Nette\DI\ExpandFunctionToStaticExpandFunctionRector: ~
    Rector\Rector\Contrib\Nette\DI\CompilerCompileArgumentsRector: ~
    Rector\Rector\Contrib\Nette\DI\CompilerGenerateCodeArgumentsRector: ~

    # forms
    Rector\Rector\Contrib\Nette\Forms\ChoiceDefaultValueRector: ~
    Rector\Rector\Contrib\Nette\Forms\FormNegativeRulesRector: ~
    Rector\Rector\Contrib\Nette\Forms\FormCallbackRector: ~

    Rector\Rector\MagicDisclosure\GetAndSetToMethodCallRector:
        $typeToMethodCalls:
            # di
            'Nette\DI\Container':
                'get': 'getService'
                'set': 'setService'

    Rector\Rector\MagicDisclosure\UnsetAndIssetToMethodCallRector:
        $typeToMethodCalls:
            # di
            'Nette\DI\Container':
                'isset': 'hasService'
                'unset': 'removeService'

    Rector\Rector\Dynamic\MethodNameReplacerRector:
        $perClassOldToNewMethods:
            # application
            'Nette\Application\UI\Control':
                'invalidateControl': 'redrawControl'

            # di
            'Nette\DI\ServiceDefinition':
                'setImplementType': 'setImplementMode'
                'getImplementType': 'getImplementMode'

            # forms
            'Nette\Bridges\FormsLatte\FormMacros':
                'renderFormBegin': ['Nette\Bridges\FormsLatte\Runtime', 'renderFormBegin']
                'renderFormEnd': ['Nette\Bridges\FormsLatte\Runtime', 'renderFormEnd']

            # php-generator
            'Nette\PhpGenerator\ClassType':
                'addDocument': 'addComment'
                'setDocuments': 'setComment'
                'getDocuments': 'getComment'
            'Nette\PhpGenerator\Method':
                'addDocument': 'addComment'
                'setDocuments': 'setComment'
                'getDocuments': 'getComment'
            'Nette\PhpGenerator\PhpFile':
                'addDocument': 'addComment'
                'setDocuments': 'setComment'
                'getDocuments': 'getComment'
            'Nette\PhpGenerator\Property':
                'addDocument': 'addComment'
                'setDocuments': 'setComment'
                'getDocuments': 'getComment'

            # utils
            'Nette\Utils\Html':
                'add': 'addHtml'
