services:
    Rector\Rector\Dynamic\ClassReplacerRector:
        $oldToNewClasses:
            'Environment': 'Nette\Environment'
            'Image': 'Nette\Image'
            'IRouter': 'Nette\Application\IRouter'
            'IHttpRequest': 'Nette\Http\IRequest'
            'PresenterRequest': 'Nette\Application\Request'
            'Presenter': 'Nette\Application\UI\Presenter'
            'Component': 'Nette\ComponentModel\Component'
