services:
    Rector\Rector\Contrib\Nette\Application\InjectPropertyRector: ~
    Rector\Rector\Dynamic\ClassReplacerRector:
        $oldToNewClasses:
            'Nette\Config\Configurator': 'Nette\Configurator'
