services:
    _defaults:
        autowire: true
        public: true # for tests

    # PhpParser - Parser
    PhpParser\Parser:
        factory: ['@Rector\Parser\ParserFactory', 'create']
    PhpParser\Lexer:
        factory: ['@Rector\Parser\LexerFactory', 'create']
    PhpParser\ParserFactory: ~
    PhpParser\BuilderFactory: ~

    PhpParser\NodeVisitor\CloningVisitor:
    PhpParser\NodeVisitor\NameResolver:
        arguments:
            $options:
                # keep nodes the same, so the code can be saved without name changes
                'replaceNodes': false

    PhpParser\NodeTraverser: ~

    # value resolver
    PhpParser\ConstExprEvaluator:
        factory: ['@Rector\NodeValueResolver\ConstExprEvaluatorFactory', 'create']

    # Symfony\Console
    Symfony\Component\Console\Style\SymfonyStyle: ~

    Symfony\Component\Console\Input\ArgvInput: ~

    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
