services:
    _defaults:
        autowire: true
        public: true # for tests

    Rector\:
        resource: '../'
        exclude: '../{Node/Attribute.php,Rector/**/*Rector.php,Rector/**/*RectorProvider.php,Reporting/FileDiff.php,Testing}'

    Rector\Rector\Contrib\Symfony\Form\Helper\FormTypeStringToTypeProvider: ~

    # prepares helper attributes of nodes
    Rector\NodeTraverser\StandaloneTraverseNodeTraverser:
        # order matters, so the next NodeVisitor can work with previous' attributes
        calls:
            # adds FQN names for elements
            # adds previous, next and parent node via attribute
            # adds current class and method to all nodes via attribute
            # adds current namespace to all nodes via attribute (have to be before TypeResolver)
            - ['addNodeVisitors', [['@PhpParser\NodeVisitor\CloningVisitor', '@PhpParser\NodeVisitor\NameResolver', '@Rector\NodeVisitor\NodeConnector', '@Rector\NodeTypeResolver\NodeVisitor\ClassAndMethodResolver', '@Rector\NodeTypeResolver\NodeVisitor\NamespaceResolver']]]

            # adds type to variable and property nodes via attribute
            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\TypeNodeVisitor']]
