services:
    Rector\Rector\Contrib\PHPUnit\ExceptionAnnotationRector: ~
    Rector\Rector\Contrib\PHPUnit\GetMockRector: ~

    # ref. https://github.com/sebastianbergmann/phpunit/compare/5.7.9...6.0.0
    Rector\Rector\Dynamic\PseudoNamespaceToNamespaceRector:
        $configuration:
            - 'PHPUnit_'
            # exclude this class, since it has no namespaced replacement
            - '!PHPUnit_Framework_MockObject_MockObject'

    # handles 2nd and 3rd argument of setExpectedException
    Rector\Rector\Contrib\PHPUnit\DelegateExceptionArgumentsRector: ~

    Rector\Rector\Dynamic\MethodNameReplacerRector:
        $perClassOldToNewMethods:
            'PHPUnit\Framework\TestClass':
                'setExpectedException': 'expectedException'
                'setExpectedExceptionRegExp': 'expectedException'
