services:
    Rector\Rector\Contrib\Symfony\FrameworkBundle\ContainerGetToConstructorInjectionRector: ~
    Rector\Rector\Contrib\Symfony\FrameworkBundle\GetParameterToConstructorInjectionRector: ~
    Rector\Rector\Contrib\Symfony\FrameworkBundle\GetToConstructorInjectionRector: ~
